#db_table columns

companytable ='companies'
branchestable ='branches'
branchbankdetails = 'branch_bank_details'
productgroupstable = 'product_groups'
productcategoriestable = 'product_categories'
productstockunitstable = 'product_stock_units'
productgstclassificationstable = 'product_gst_classifications'
productsalesgltable = 'product_sales_gl'
productpurchasegltable ='product_purchase_gl'
productstable = 'products'

#db_table masters columns
countrytable = 'country'
statetable = 'state'
citytable = 'city'
statusestable = 'statuses'
producttypestable = 'product_types'
productuniquequantitycodestable = 'product_unique_quantity_codes'
unitoptionstable = 'unit_options'
productdrugtypestable = 'product_drug_types'
productitemtypetable = 'product_item_type'
brandsalesmantable = 'brand_salesman'
productbrandstable = 'product_brands'