# Generated by Django 4.2.6 on 2024-04-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('print_name', models.CharField(max_length=255)),
                ('identification', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('ledger_account_id', models.PositiveIntegerField()),
                ('customer_common_for_sales_purchase', models.BooleanField(default=False)),
                ('is_sub_customer', models.BooleanField(default=False)),
                ('firm_status_id', models.PositiveIntegerField()),
                ('territory_id', models.PositiveIntegerField()),
                ('customer_category_id', models.PositiveIntegerField()),
                ('contact_person', models.CharField(max_length=255)),
                ('picture', models.CharField(max_length=255)),
                ('gst', models.CharField(max_length=50)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('cin', models.CharField(max_length=50)),
                ('pan', models.CharField(max_length=50)),
                ('gst_category_id', models.PositiveIntegerField()),
                ('gst_suspend', models.BooleanField(default=False)),
                ('tax_type', models.CharField(choices=[('Inclusive', 'Inclusive'), ('Exclusive', 'Exclusive')], default='Inclusive', max_length=10)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('tds_on_gst_applicable', models.BooleanField(default=False)),
                ('tds_applicable', models.BooleanField(default=False)),
                ('website', models.CharField(max_length=255)),
                ('facebook', models.CharField(max_length=255)),
                ('skype', models.CharField(max_length=255)),
                ('twitter', models.CharField(max_length=255)),
                ('linked_in', models.CharField(max_length=255)),
                ('payment_term_id', models.PositiveIntegerField()),
                ('price_category_id', models.PositiveIntegerField()),
                ('batch_rate_category', models.CharField(max_length=50)),
                ('transporter_id', models.PositiveIntegerField()),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=18)),
                ('max_credit_days', models.IntegerField()),
                ('interest_rate_yearly', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
