# Generated by Django 4.2.7 on 2024-04-18 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '__first__'),
        ('masters', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouses',
            fields=[
                ('warehouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('pin_code', models.CharField(default=None, max_length=50, null=True)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, default=None, max_digits=10, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, default=None, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city_id', models.ForeignKey(db_column='city_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.city')),
                ('customer_id', models.ForeignKey(db_column='customer_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('item_type_id', models.ForeignKey(db_column='item_type_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.productitemtype')),
            ],
            options={
                'db_table': 'warehouses',
            },
        ),
    ]
